services:
  - type: web
    name: malaria-detection-app
    env: python
    pythonVersion: "3.10"  # Explicit Python version
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 1 -b 0.0.0.0:$PORT app:app
    envVars:
      - key: PORT
        value: $PORT  # Use Render's dynamic port
